// Librairies
import './globals.css';
import { Inter } from 'next/font/google';

// Variable 1 - inter
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Eternal NFT By adelamare-blockchain',
  description: 'Generated by create next app',
};

// MAIN FUNCTION
export default function RootLayout({ children }) {
  // Rendu JSX
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
